name: CI
on:
    push:
      branches: [ "main" ]

env:
    VERSION: 1.0.24-3

jobs:
  debian-x86_build:
    runs-on: ubuntu-latest
    container: debian
    strategy:
      matrix:
        include:
          - arch: armhf
            extra_dep: crossbuild-essential-armhf

    env:
        CROSS: ${{ matrix.arch != 'amd64' || matrix.arch != 'i386' }}
        DEP: sudo devscripts debian-keyring pkg-config docbook docbook-dsssl libudev-dev doxygen debhelper build-essential tree
        FetchSource: dget http://deb.debian.org/debian/pool/main/libu/libusb-1.0/libusb-1.0_${VERSION}.dsc
        CONFIG_SITE: /etc/dpkg-cross/cross-config.amd64
          #DEB_BUILD_OPTIONS: nocheck

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
          
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v3

      - name: Add architecture for dpkg if needed
        run: ${{ env.CROSS }} && dpkg --add-architecture ${{ matrix.arch }}

      - name: Prepare for build
        run: apt update && apt install ${{ env.DEP }} ${{ matrix.extra_dep }} -y


      - name: Fetch application source
        run: apt build-dep -a${{matrix.arch}} libusb-1.0 || ${{ env.FetchSource }}

      - name: Apply patch
        run: |
          tree
          echo "-------------------------------------------"
          sh -c "ls patch | xargs cat | patch -d libusb-1.0* -t -p1 -R"

      - name: Build
        run: |
                cd libusb*/
                ${{ env.CROSS }} && set -- $@ -a${{ matrix.arch}} -Pcross
                dpkg-buildpackage $@
                cd ../

      - name: Generate files list
        run: |
          tree > filelist-${{matrix.arch}}.tree

      - name: Releases Files 
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: libusb-1.0_${{env.VERSION}}-test-lastest
          files: |
            ./filelist*.tree
            **/*.deb
            **/*.udeb
